JAVAC=javac
JAVA=java
CLASSES=DungeonHunterParallel.java DungeonMapParallel.java HuntParallel.java
ARGS?=20 0.2 0

all:
	$(JAVAC) $(CLASSES)

run:
	$(JAVA) DungeonHunterParallel $(ARGS)

clean:
	rm -f *.class